# Generated by Django 2.1.4 on 2019-02-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_auto_20190202_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('key_text', models.TextField()),
                ('word_count', models.PositiveSmallIntegerField()),
                ('key_word_count', models.PositiveSmallIntegerField()),
                ('sentiment_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sentiment_magnitude', models.DecimalField(decimal_places=1, max_digits=2)),
                ('num_questions', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('key_text', models.TextField()),
                ('begin_offset', models.PositiveSmallIntegerField()),
                ('word_count', models.PositiveSmallIntegerField()),
                ('keyWord_count', models.PositiveSmallIntegerField()),
                ('sentiment_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sentiment_magnitude', models.DecimalField(decimal_places=1, max_digits=2)),
                ('question', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Attendee')),
            ],
        ),
        migrations.RemoveField(
            model_name='meetingmember',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetingmember',
            name='profile',
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(default='gay description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='key_text',
            field=models.TextField(default='gay key text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='key_word_count',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='sentiment_magnitude',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='word_count',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='MeetingMember',
        ),
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Meeting'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Profile'),
        ),
    ]
