# Generated by Django 2.1.4 on 2019-02-03 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverapp', '0003_auto_20190203_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='profile',
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
