# Generated by Django 2.1.5 on 2019-02-03 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_auto_20190203_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='keyWord_count',
            new_name='key_word_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Calvin', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
